### PR TITLE
Fix windows compatibility of memwatch.cc

### PR DESCRIPTION
**Pull request by curvedriver**
Fixes windows compatibility of memwatch.cc which is broken since #3 .
I used `uv_hrtime()` instead of gettimeofday to get `gc_ts` in microseconds.

`npm install` of v1.0.2 and v.2.0.0 shows the following error on a windows machine:

```
C:\work\myproject\node_modules\@airbnb\node-memwatch\src\memwatch.cc(19): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory [C:\work\myproject\node_modules\@airbnb\node-memwatch\build\memwatch.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\work\myproject\node_modules\@airbnb\node-memwatch
gyp ERR! node -v v10.22.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})    

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @airbnb/node-memwatch@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @airbnb/node-memwatch@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### CODE REVIEW

**Comment by curvedriver** [comment]
Hi @schleyfox ,
any progress regarding the review?

**Comment by curvedriver** [comment]
any updates?

**Comment by jpl-ivengi** [comment]
@schleyfox any idea when you might be able to perform the review?

**Comment by curvedriver** [comment]
@ljharb , 
could another reviewer inspect this PR? 

@schleyfox isn't responsive...

**Comment by curvedriver** [comment]
@ljharb , @schleyfox ?

File: package.json [hunk 1]
```diff
@@ -1,7 +1,7 @@
 {
   "name": "@airbnb/node-memwatch",
   "description": "Keep an eye on your memory usage, and discover and isolate leaks.",
-  "version": "2.0.0",
+  "version": "2.0.1",
```
Comment (ljharb) [inline package.json:4]: version numbers aren't updated in PRs; this should be reverted.

File: ChangeLog [hunk 2]
```diff
@@ -1,3 +1,6 @@
+v2.0.1
```
Comment (ljharb) [inline ChangeLog:1]:
```suggestion
Unreleased
```

**Review by ljharb — COMMENTED** [review]
I'm not really capable of reviewing the C code, but I do note that there's no tests covering the change.

File: package.json [hunk 3]
```diff
@@ -24,7 +24,7 @@
     "test": "mocha tests --reporter spec"
   },
   "devDependencies": {
-    "mocha": "^2.4.5",
+    "mocha": "^9.2.0",
```
Comment (ljharb) [inline package.json:27]: mocha 9 requires node 12; this package supports node 10. you'll need to use mocha 7 (since mocha 8 requires 10.12, and this package supports 10.0)

File: tests.js [hunk 4]
```diff
@@ -14,10 +18,23 @@ describe('the library', function() {
...
+
     memwatch.once('stats', function(s) {
+      const timeAfterEvent = hrtimeInMicroseconds();
+
       s.should.be.object;
+
+      (typeof timeBeforeGc).should.equal("bigint");
+      timeAfterEvent.should.be.greaterThan(timeBeforeGc);
+
+      s.gc_ts.should.be.a.Number()
```
Comment (ljharb) [inline tests.js:31]:
```suggestion
      s.gc_ts.should.be.a.Number();
```

**Comment by ljharb** [comment]
@curvedriver seems like your latest push messed up the PR? can you restore the branch and reopen it?
